namespace AgroSynapse.Resources.Splash;

public partial class Splash : ContentPage
{
    public Splash()
    {
        InitializeComponent(); // Ensure this method is generated by the XAML compiler
        StartSplashScreen();
    }

    private async void StartSplashScreen()
    {
        await Task.Delay(5000); // Aguarda 5 segundos
        Application.Current.MainPage = new AppShell(); // Navega para a tela principal
    }
}